meal_plans/urls.py
from django.urls import path

from meal_plans.views import (
    MealPlanListView,
    MealPlanDetailView,
    MealPlanDeleteView,
    MealPlanCreateView,
    MealPlanUpdateView,
)
   

urlpatterns = [
    path("", MealPlanListView.as_view(), name="mealplans_list"),
    path("<int:pk>/", MealPlanDetailView.as_view(), name="mealplan_detail"),
    path("<int:pk>/delete/", MealPlanDeleteView.as_view(), name="mealplan_delete"),
    path("create/", MealPlanCreateView.as_view(), name="mealplan_create"),
    path("<int:pk>/edit/", MealPlanUpdateView.as_view(), name="mealplan_edit"),
]

scrumptious/urls.py
from django.contrib import admin
from django.urls import include, path, reverse_lazy
from django.views.generic.base import RedirectView
from django.contrib.auth import views as auth_views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("recipes/", include("recipes.urls")),
    path("tags/", include("tags.urls")),
    path("meal_plans/", include("meal_plans.urls")),
    path(
        "",
        RedirectView.as_view(url=reverse_lazy("recipes_list")),
        name="home",
    ),
    path("accounts/login/", auth_views.LoginView.as_view(), name="login"),
    path("accounts/logout/", auth_views.LogoutView.as_view(), name="logout"),
]

tags/urls.py
from django.urls import path

from tags.views import (
    TagListView,
    TagDeleteView,
    TagDetailView,
    TagCreateView,
    TagUpdateView,
)

urlpatterns = [
    path("", TagListView.as_view(), name="tags_list"),
    path("<int:pk>/", TagDetailView.as_view(), name="tag_detail"),
    path("<int:pk>/delete/", TagDeleteView.as_view(), name="tag_delete"),
    path("new/", TagCreateView.as_view(), name="tag_new"),
    path("<int:pk>/edit/", TagUpdateView.as_view(), name="tag_edit"),
]

meal_plans/models.py
from django.db import models
from django.conf import settings

USER_MODEL = settings.AUTH_USER_MODEL

# Create your models here.
class MealPlan(models.Model):
    name = models.CharField(max_length=120)
    date = models.DateTimeField(auto_now=False)
    owner = models.ForeignKey(USER_MODEL, on_delete=models.CASCADE)
    recipes = models.ManyToManyField("recipes.Recipe", related_name="recipes")

    def __str__(self):
        return self.name

meal_plans/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.db import models

from meal_plans.models import MealPlan

# Create your views here.
# list view
class MealPlanListView(ListView):
    model = MealPlan
    template_name = "meal_plans/list.html"
    paginate_by = 8

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)
# create view
class MealPlanCreateView(LoginRequiredMixin, CreateView):
    model = MealPlan
    template_name = "meal_plans/new.html"
    fields = ["name", "date", "recipes"]
    success_url = reverse_lazy("mealplan_detail")

    def form_valid(self, form):
        plan = form.save(commit=False)
        plan.owner = self.request.user
        plan.save()
        form.save_m2m()
        return redirect("mealplan_detail", pk=plan.id)

# detail view
class MealPlanDetailView(DetailView):
    model = MealPlan
    template_name = "meal_plans/detail.html"

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

# edit view
class MealPlanUpdateView(LoginRequiredMixin, UpdateView):
    model = MealPlan
    template_name = "meal_plans/edit.html"
    fields = ["name", "date", "recipes"]

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

    def get_success_url(self):
        return reverse_lazy("mealplan_detail", args=[self.object.id])

# delete view
class MealPlanDeleteView(LoginRequiredMixin, DeleteView):
    model = MealPlan
    template_name = "meal_plans/delete.html"
    success_url = reverse_lazy("mealplans_list")

    def get_queryset(self):
        return MealPlan.objects.filter(owner=self.request.user)

meal_plans/templates/meal_plans/delete.html
{% extends 'base.html' %}

{% block content %}
<main>
    <form method="post">
        {% csrf_token %}
        <p>Are you sure you want to delete your mealplan: "{{ mealplan }}" ?</p>
        {{ form.as_p }}
        <div class="control">
            <button class="button">Delete</button>
        </div>
    </form>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/detail.html
{% extends 'base.html' %}
{% load markdownify %}

{% block content %}
<main class="recipe-detail">
    <div>
        <a href="{% url 'mealplan_edit' mealplan.pk %}">Edit</a>
        <a href="{% url 'mealplan_delete' mealplan.pk %}">Delete</a>
    </div>
    <h1>{{ mealplan.name }}</h1>
    <h2>by: {{ mealplan.owner | default_if_none:"Unknown" }}</h2>
    <p>
        To be served on {{ mealplan.date }}
    </p>
    <p>
        {% for recipe in mealplan.recipes.all %}
        <a href="{% url 'recipe_detail' recipe.pk %}"> {{ recipe.name }} |</a>
        {% endfor %}
    </p>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/edit.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
    <h2>Edit
        <a href="{% url 'mealplan_detail' mealplan.pk %}">{{ mealplan.name }}</a>
        :
    </h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button">Update</button>
        </div>
    </form>
</main>
{% endblock content %}

meal_plans/templates/meal_plans/list.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-grid">
    <h2>List of Mealplans:</h2>
    {% for mealplan in mealplan_list %}
    <div class="recipe-card">
        <h2 class="recipe-card-title">
            <a href="{% url 'mealplan_detail' mealplan.pk %}">{{ mealplan.name }}</a>
        </h2>
        <p class="recipe-card-date">{{ mealplan.updated }}</p>
        {% for recipe in mealplan.recipes.all %}
        <p>
            <a href="{% url 'recipe_detail' recipe.pk %}"> {{ recipe.name }} |</a>
        </p>
        {% endfor %}
    </div>
    {% empty %}
    <div>
        <h2>No Mealplans yet.</h2>
        <p>
            Would you like to
            <a href="{% url 'mealplan_create' %}">create</a>
            a meal plan?
        </p>
    </div>
    {% endfor %}
</main>
{% endblock content %}

{% block pagination %}
<div class="pagination">
    <span class="step-links">
        {% if page_obj.has_previous %}
        <a href="?page=1">&laquo; first</a>
        <a href="?page={{ page_obj.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}.
        </span>

        {% if page_obj.has_next %}
        <a href="?page={{ page_obj.next_page_number }}">next</a>
        <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>
{% endblock pagination %}

meal_plans/templates/meal_plans/new.html
{% extends 'base.html' %}

{% block content %}
<main class="recipe-form">
    <h2>Create a Mealplan:</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <div class="control">
            <button class="button">Create</button>
        </div>
    </form>
</main>
{% endblock content %}